### ISSUE TITLE
RedCokeDevelopment/MCServerPing MIT License Attribution

### ISSUE THREAD

**Issue by RedTeaDev** [EnhancedPlugins/EnhancedBungeeMOTD#1]
Hello Luca, I am one of the developers of the resource "RedCokeDevelopment/MCServerPing". I would like to inform you that our resource is licensed under MIT License, and we suggest you to follow the license guidelines and include the copyright notice "Copyright (c) 2020-2022 Red Coke Development" and permission notice of our MIT License file located at https://github.com/RedCokeDevelopment/MCServerPing/blob/master/LICENSE in all the classes from our resource. Thank you for your attention, have a nice day.

For further information, you can take a look at https://opensource.stackexchange.com/questions/4506/what-license-do-i-apply-to-my-software-if-parts-of-its-code-is-derived-from-mit

**Comment by einlichtvogel** [comment]
Hello :)
Oh yes, of course I will.
I am very sorry, I'm not very good at this licensing thing, thanks for the advice.
I will immediately add it to the code.
Is the following right @RedTeaDev ?

<img width="676" alt="Bildschirmfoto 2022-01-28 um 10 20 13" src="https://user-images.githubusercontent.com/65811753/151520548-60ec1a29-8f27-479c-8752-8674cc30ce72.png">

**Comment by einlichtvogel** [comment]
I have also added the same comment in McServerPingResponse...
And sorry for the late answer!

**Comment by RedTeaDev** [comment]
Yup that’s perfect, sorry for my late response since I was out of office over the lunar new year holidays, thank you for your time and have a nice day!
